<b>Тип:</b> <i>{{ $type }}</i>
<b>ФИО:</b> <i>{{ $FIO }}</i>
<b>Телефон:</b> <i>{{ $FIO }}</i>
<b>E-mail:</b> <i>{{ $mail }}</i>
<b>Область:</b> <i>{{ $region }}</i>
<b>Город:</b> <i>{{ $city }}</i>
<b>Улица:</b> <i>{{ $street }}</i>
<b>Дом:</b> <i>{{ $house }}</i>
<b>Отделение:</b> <i>{{ $warehouse }}</i>
<b>Доставка:</b> <i>{{ $delivery }}</i>
<b>Оплата:</b> <i>{{ $payment }}</i>
<b>Комментарий:</b> <i>{{ $comment }}</i>
